[package]
name = "ggml-llama-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
wasi-nn = { package = "wasmedge-wasi-nn", git = "https://github.com/second-state/wasmedge-wasi-nn", branch = "ggml" }
